name: Build APK

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '14742923'
        packages: 'platforms;android-37.0 build-tools;37.0.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=0 \
          --install "ndk;29.0.14206865"
        echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV

    - name: Restore cached libhevtun
      id: cache-libhevtun-restore
      uses: actions/cache/restore@v6
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh', 'patches/*.patch') }}

    - name: Build libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      run: |
        bash compile-hevtun.sh
    
    - name: Save libhevtun
      if: steps.cache-libhevtun-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v6
      with:
        path: ${{ github.workspace }}/libs
        key: libhevtun-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hev-socks5-tunnel/HEAD') }}-${{ hashFiles('compile-hevtun.sh', 'patches/*.patch') }}

    - name: Copy libhevtun
      run: |
        cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app

    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version: '1.27.1'

    - name: Build Xray and sing-box mobile bundle
      run: |
        go install github.com/sagernet/gomobile/cmd/gomobile@v0.1.13
        go install github.com/sagernet/gomobile/cmd/gobind@v0.1.13
        cd AndroidCoreBundle
        bash build.sh

    - name: Setup Java
      uses: actions/setup-java@v5.6.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Decode release keystore
      uses: timheuer/base64-to-file@v2.0.0
      id: release_keystore
      with:
        fileName: freedom-release.jks
        encodedString: ${{ secrets.APP_KEYSTORE_BASE64 }}

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod 755 gradlew
        ./gradlew licenseFdroidReleaseReport
        ./gradlew assembleFdroidRelease \
          -PABI_FILTERS=arm64-v8a \
          -Pandroid.injected.signing.store.file=${{ steps.release_keystore.outputs.filePath }} \
          -Pandroid.injected.signing.store.password=${{ secrets.APP_KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }}
    
    - name: Upload arm64-v8a APK
      uses: actions/upload-artifact@v7
      if: ${{  success() }}
      with:
        name: arm64-v8a
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*/release/*arm64-v8a*.apk

  sign-and-release:
    needs: build
    runs-on: ubuntu-26.04
    if: github.event_name == 'workflow_dispatch' && inputs.release_tag != ''

    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v8
        with:
          path: release

      - name: Collect APK files
        run: |
          mkdir -p release-files
          find release -type f -name '*.apk' -exec cp {} release-files/ \;

      - name: Upload ARM64 APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: release-files/*
          tag: ${{ inputs.release_tag }}
          file_glob: true
          prerelease: false
